name: detoxifier
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip<24.1
  - numpy>=1.21,<1.22
  - pandas>=1.3,<1.4
  - scikit-learn>=0.24,<0.25
  - matplotlib>=3.5,<3.6
  - nltk>=3.6,<3.7
  - tqdm>=4.62,<4.65
  - sentencepiece>=0.1.96
  - pip:
      - torch>=2.1.0
      - torchvision>=0.16
      - torchaudio>=2.1
      - transformers>=4.28
      - datasets>=2.13
      - sentence-transformers==2.1.0
      - fastBPE==0.1.0
      - sacremoses==0.0.53
      - textblob
      - langdetect
      - git+https://github.com/bheinzerling/pyrouge.git
      - git+https://github.com/facebookresearch/fairseq.git

