name: detoxifier
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - numpy>=1.21,<1.22
  - pandas>=1.3,<1.4
  - scikit-learn>=0.24,<0.25
  - matplotlib>=3.5,<3.6
  - nltk>=3.6,<3.7
  - tqdm>=4.62,<4.65
  - sentencepiece>=0.1.96
  - pip:
      - torch>=1.12,<2
      - torchaudio>=0.12,<0.13
      - torchvision>=0.13,<0.14
      - transformers>=4.25,<5
      - datasets>=2.14,<3
      - sentence-transformers>=2.2,<3
      - textblob
