name: detoxifier
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - scikit-learn
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - nltk
  - tqdm
  - sentencepiece
  - tensorboard
  - pip:
      - torch==2.2.2
      - torchvision==0.17.2
      - torchaudio==2.2.2
      - transformers==4.9.2
      - datasets==1.11.0
      - sentence-transformers==2.1.0
      - fairseq==0.12.2
      - fastBPE==0.1.0
      - sacremoses==0.0.53
      - textblob
      - git+https://github.com/bheinzerling/pyrouge.git
