name: mdtox-binder
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - pip
  - pip:
      # Ensure pip <24.1 to avoid metadata issues
      - pip<24.1

      # Core ML/NLP packages
      - torch==1.12.1
      - torchvision==0.13.1
      - torchaudio==0.12.1
      - transformers==4.9.2
      - datasets==2.13.0
      - sentence-transformers==2.1.0

      # Detox/masking packages
      - fastBPE==0.1.0
      - sacremoses==0.0.53
      - textblob
      - langdetect
      - git+https://github.com/bheinzerling/pyrouge.git

      # Fairseq (compatible with torch 1.12)
      - fairseq==0.12.2
