name: detoxifier
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - tqdm
  - jupyterlab
  - pip
  - pip:
      - torch>=1.12,<2
      - torchaudio>=0.12,<2
      - transformers
