name: detoxifier
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  # Kernpakete
  - python=3.9
  - numpy>=1.21,<1.22
  - pandas>=1.3,<1.4
  - scikit-learn>=0.24,<0.25
  - matplotlib
  - nltk
  - tqdm
  - sentencepiece
  - pip
  - cython
  - setuptools

  # PyTorch (CPU automatisch)
  - pytorch=1.9.1
  - torchvision=0.10.1
  - torchaudio=0.9.1

  # Pip-Pakete
  - pip:
      - transformers==4.9.2
      - datasets==1.11.0
      - sentence-transformers==2.1.0
      - git+https://github.com/pytorch/fairseq.git@v0.10.2
      - fastBPE==0.1.0
      - sacremoses==0.0.53
      - textblob
      - git+https://github.com/bheinzerling/pyrouge.git@master
