name: mdetoxifier
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - cython
  - numpy
  - setuptools
  - pandas
  - nltk
  - matplotlib
  - tqdm
  - pyarrow
  - sentencepiece
  - pip:
      - datasets==2.13.0
      - transformers==4.9.2
      - sentence-transformers==2.1.0
      - torch==1.9.1
      - torchvision==0.10.1
      - torchaudio==0.9.1
      - fastBPE==0.1.0
      - sacremoses==0.0.53
      - textblob
      - langdetect
      - git+https://github.com/bheinzerling/pyrouge.git
      - git+https://github.com/facebookresearch/fairseq.git@main
