name: detoxifier
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - torch==1.9.0
      - torchvision==0.10.0
      - torchaudio==0.9.0
      - transformers==4.9.2
      - sentencepiece==0.1.96
      - sacremoses==0.0.53
      - nltk==3.6.2
      - scikit-learn==0.24.2
      - numpy==1.21.2
      - pandas==1.3.3
      - tqdm==4.62.2
      - matplotlib==3.4.3
      - seaborn==0.11.2
      - tensorboard==2.6.0
      - tensorboardX==2.4
      - datasets==1.11.0
      - sentence-transformers==2.1.0
      - fairseq==0.10.2
      - fastBPE==0.1.0
      - git+https://github.com/bheinzerling/pyrouge.git
